<?php
/**
 * TVfrog - First-time setup wizard
 * Creates config.php with your admin password.
 */

$configPath = __DIR__ . '/config.php';

if (file_exists($configPath)) {
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        header('Content-Type: application/json');
        echo json_encode(['error' => 'Already configured.']);
        exit;
    }
    echo "<!DOCTYPE html><html><body style='font-family:sans-serif;text-align:center;padding:60px;'>
        <h2>TVfrog is already configured</h2>
        <p>Delete admin/api/config.php to reconfigure.</p>
        <a href='../../'>Go to TVfrog</a>
    </body></html>";
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    header('Content-Type: application/json');
    $password = trim($_POST['password'] ?? '');

    if (strlen($password) < 6) {
        echo json_encode(['error' => 'Password must be at least 6 characters.']);
        exit;
    }

    $hash = password_hash($password, PASSWORD_BCRYPT);

    $config = "<?php\n";
    $config .= "// TVfrog Configuration - Generated by setup wizard\n";
    $config .= "// Date: " . date('Y-m-d H:i:s') . "\n\n";
    $config .= "\$adminPasswordHash = " . var_export($hash, true) . ";\n";

    if (file_put_contents($configPath, $config) === false) {
        echo json_encode(['error' => 'Could not write config.php. Check folder permissions.']);
        exit;
    }

    // Create default data file
    $dataPath = __DIR__ . '/../../data/app_data.json';
    if (!file_exists($dataPath)) {
        @mkdir(dirname($dataPath), 0755, true);
        $defaultData = [
            'userLists' => ['Favourites' => [], 'Watchlist' => [], 'Seen' => [], 'To Finish' => []],
            'followedShows' => [],
            'showData' => (object)[]
        ];
        file_put_contents($dataPath, json_encode($defaultData, JSON_PRETTY_PRINT));
    }

    echo json_encode(['success' => true]);
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TVfrog Setup</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, sans-serif; background: #f2f2f7; min-height: 100vh; display: flex; align-items: center; justify-content: center; }
        .card { background: #fff; border-radius: 16px; padding: 40px; max-width: 420px; width: 90%; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
        h1 { font-size: 1.6em; margin-bottom: 8px; }
        p { color: #8e8e93; margin-bottom: 24px; font-size: 0.9em; line-height: 1.5; }
        label { display: block; font-weight: 600; font-size: 0.85em; margin-bottom: 4px; margin-top: 16px; }
        input { width: 100%; padding: 10px 14px; border: 1px solid #d1d1d6; border-radius: 10px; font-size: 0.95em; font-family: inherit; }
        input:focus { outline: none; border-color: #007aff; }
        .hint { font-size: 0.78em; color: #8e8e93; margin-top: 4px; }
        button { width: 100%; padding: 12px; margin-top: 24px; border: none; border-radius: 12px; background: #007aff; color: #fff; font-size: 1em; font-weight: 600; cursor: pointer; font-family: inherit; }
        button:hover { opacity: 0.9; }
        button:disabled { opacity: 0.5; }
        .msg { margin-top: 12px; padding: 10px; border-radius: 8px; font-size: 0.88em; display: none; }
        .msg.err { background: #fee2e2; color: #991b1b; display: block; }
        .msg.ok { background: #d1fae5; color: #065f46; display: block; }
    </style>
</head>
<body>
    <div class="card">
        <h1>Welcome to TVfrog</h1>
        <p>Set up your instance. Choose an admin password to manage your TV show lists. No API key needed — TVfrog uses the free TVMaze API.</p>

        <form id="setupForm">
            <label for="password">Admin Password</label>
            <input type="password" id="password" name="password" placeholder="Min 6 characters" required minlength="6">
            <div class="hint">Used to manage your TV show lists and follow shows</div>

            <button type="submit" id="submitBtn">Set Up TVfrog</button>
        </form>

        <div id="msg" class="msg"></div>
    </div>

    <script>
    document.getElementById('setupForm').addEventListener('submit', async (e) => {
        e.preventDefault();
        const btn = document.getElementById('submitBtn');
        const msg = document.getElementById('msg');
        btn.disabled = true; btn.textContent = 'Setting up...';
        msg.className = 'msg'; msg.style.display = 'none';

        const fd = new FormData(e.target);
        try {
            const r = await fetch('setup.php', { method: 'POST', body: fd });
            const d = await r.json();
            if (d.success) {
                msg.className = 'msg ok'; msg.textContent = 'Setup complete! Redirecting...'; msg.style.display = 'block';
                setTimeout(() => window.location.href = '../../', 1500);
            } else {
                msg.className = 'msg err'; msg.textContent = d.error; msg.style.display = 'block';
                btn.disabled = false; btn.textContent = 'Set Up TVfrog';
            }
        } catch (err) {
            msg.className = 'msg err'; msg.textContent = 'Connection error.'; msg.style.display = 'block';
            btn.disabled = false; btn.textContent = 'Set Up TVfrog';
        }
    });
    </script>
</body>
</html>
